#ifndef CHAR_UTILS_CONSTANTS_H
#define CHAR_UTILS_CONSTANTS_H
// CHAR_UTILS CONSTANTS
constexpr char NULL_TERMINATOR = '\0';
constexpr int NULL_TERMINATOR_NOT_PRESENT = -1;

// ERROR RETURN VALUES
constexpr int ERROR_NO_NULL_TERMINATOR = -1;

#endif // CHAR_UTILS_CONSTANTS_H